export { default as About } from "./About";
export { default as Portfolio } from "./Portfolio";
export { default as Resume } from "./resume";
export { default as Home } from "./Home";
export { default as RightNav } from "./RightNav";
export { default as Toggle } from "./Toggle";
export { default as Navbar } from "./Navbar";
export { default as Burger } from "./Burger";
export { default as Landing } from "./Landing";
